### ISSUE TITLE
App Development for Milestone 2

### ISSUE THREAD

**Issue by camharris22** [UBC-MDS/dsci-532_group-20#15]
## 3. Interactive Dash app in Python and Altair
rubric={accuracy:10, quality:5, viz:15}

- Implement the dashboard you outlined in your proposal.
- Keep your usage scenario and target audience in mind when designing your interface.
- Aim to implement most of your dashboard's functionality, but not everything.
    - Since the complexity varies between proposals,
      the rough goal here is to have around 3 plots
      and most of their widgets
      and interactivity implemented
    - The app should be clearly usable,
      so focus on the most important things first.
    - In the upcoming milestones you will have time to improve your app
      based on your proposal and the feedback you have received.
    - The TAs will give you feedback on how to adjust the overall complexity
      of your final app for milestone 3 and 4 (if needed). For this milestone,
      use the above directions.
- Your interface should be as self-documenting as possible,
  with appropriate labels for panes and widgets,
  legends documenting the meaning of visual encodings,
  and a meaningful title for the app.
- Note that TAs will be grading your app on Heroku in a full-screen window

**Comment by camharris22** [comment]
I have updated the application script as per pull request:
Cleaned up layout for plots, added y histogram #16

Let me know if anyone needs any help implementing their widgets or runs into any bugs!

**Comment by chenzhao299** [comment]
We created a new `app.py` script to create our new version of dashboard and successfully deployed on Heroku.
