### ISSUE TITLE
Possible change in main plot: fix x-axis to be time

### ISSUE THREAD

**Issue by trevorki** [UBC-MDS/dsci-532_group-20#23]
Many of the plots that can be generated under the current design, where users select both x and y axes, are not very informative. 

To address this we should fix the x-axis to show time only and select the y-axis from a drop-down box.

What are your thoughts?

**Comment by camharris22** [comment]
I wonder if it would be too much work to have something like a "x-axis variable toggle button" where the default is set to "off" and the x-axis is time. But the user could toggle it "on" and change the x-axis as they wish. It sounds fairly simple to implement with a button-type widget that activates the x-axis dropdown widget.

**Comment by chenzhao299** [comment]
I have created a `app_new.py` script to select the most informative features to be visualized in the dashboard, and I also added a new slider to change the x-axis. I believe this issue is solved now.
