### ISSUE TITLE
App is very slow when using full dataset

### ISSUE THREAD

**Issue by trevorki** [UBC-MDS/dsci-532_group-20#24]
So far in development we have been using a subset of the full data to avoid the altair max rows error

This error is avoided with `alt.data_transformers.disable_max_rows()`, however it takes a 1-2 minutes for the app to load or update axes when a change is made in a drop-down box.

Joel suggested using a local data server to address this with the line `alt.data_transformers.enable("data_server")` in the starting code. This reduced the time required to 10-15 seconds. Still not fast enough, but a big improvement.

Joel also said for Millestone 2 it is ok to work with just the subset data as we will cover optimising performance in week 4.

**Comment by camharris22** [comment]
Thanks for looking into this issue Trevor. I'm supportive of using the subset data for now until week 4.

**Comment by chenzhao299** [comment]
I have used `data_server` in our new app script and subset the original dataset in the `data_wrangling.py` script to avoid the long running time. I believe it is solved now.
