### ISSUE TITLE
Dash App Examples from MDS Previous Years

### ISSUE THREAD

**Issue by chenzhao299** [UBC-MDS/dsci-532_group-20#3]
Hello everyone, @hellosakshi @trevorki @cameron

I would like to summarize all the previous examples Joel showed us in the lecture notes here, in order to make it easier for us to do brain storming on our meeting on Friday. 

- https://world-wide-weapons-report.herokuapp.com/
- https://group204-vino-milestone2.herokuapp.com/
- https://akanshav.shinyapps.io/crime_new/
- https://pall-v.shinyapps.io/wine_viz_mkpv/
- https://dsci-532-group203-maintenance.herokuapp.com/
- https://panntingg.shinyapps.io/mental_health_app_3_0/
- https://hfboyce.shinyapps.io/dsci_532-boston-crime-rate/
- https://adityashrm21.shinyapps.io/us-police-shootings-analysis/
- https://g105-milestone3.herokuapp.com/
- https://dsci-532-l02-gr212-milestone3.herokuapp.com/
- https://dsci532group114milestone3.herokuapp.com/

Let me know if you have any questions. See you on the meeting!
Chen

**Comment by trevorki** [comment]
We looked at them.
