### ISSUE TITLE
Plans for Milestone 4

### ISSUE THREAD

**Issue by chenzhao299** [UBC-MDS/dsci-532_group-20#46]
Based on the discussion during lab time within the group, and consulting with instructor and TA, we agree on trying to implement the following functions to finalize our dashboard:

- Add a new plot to show more details on different time scale
- Add cards below top plots to summarize statistics of the plots
- Add docstrings for each functions
- Restore title style to previous version and try to shrink the height
- Add an expandable button with title to show more details
- Separate global controls with local controls for variable selection
- Make legends selectable
- Deal with leap year problem
- Change name of browser's tab
- Address and reply TA feedback for milestone 2
- Try to figure out how to grey out unselectable options for second level dropdown after select the first level dropdown
- Automate deployment on Heroku
- Try to figure out update the histogram on the right based on selection of left histogram
- Write reflection for milestone 4 (remember to mention we create functions to select subset dataset from the original to improve app performance and save computations)
- Finalize `README.md` file
- Add `about` section for GitHub repo

Please refer to the above points when working on each one's parts. Feel free to propose more suggestions during the week.

**Comment by hellosakshi** [comment]
All above mentioned task were implemented.
